---
config:
  theme: base
  themeVariables:
    fontFamily: "'Open Sans', arial, sans-serif"
    primaryColor: '#cdf3ff'
    primaryTextColor: '#333E48'
    primaryBorderColor: '#007298'
    lineColor: '#45842a'
    secondaryColor: '#fff4cc'
    tertiaryColor: '#f9ccff'
---
eventmodeling
  tf 01 ui ExamplesPage
  tf 02 cmd CreateMermaidPair
  tf 03 evt MermaidPairCreated
  tf 04 rmo MermaidIndex
  tf 05 pcr ValidationRunner
  tf 06 cmd ValidateExamples
  tf 07 evt ExamplesValidated
