---
config:
  theme: base
  packet:
    bitsPerRow: 32
  themeVariables:
    fontFamily: "'Open Sans', arial, sans-serif"
    primaryColor: '#cdf3ff'
    primaryTextColor: '#333E48'
    primaryBorderColor: '#007298'
    lineColor: '#45842a'
    secondaryColor: '#fff4cc'
    tertiaryColor: '#ffccd5'
---
packet
  title Example metadata packet
  +4: "Type"
  +4: "Version"
  +8: "Palette id"
  +8: "Shape id"
  +8: "Flags"
  +32: "Diagram source length"
  +64: "Content hash"
