---
config:
  theme: base
  pie:
    textPosition: 0.55
    donutHole: 0.35
    legendPosition: bottom
    highlightSlice: Validation
  themeVariables:
    fontFamily: "'Open Sans', arial, sans-serif"
    pie1: '#cdf3ff'
    pie2: '#dbffcc'
    pie3: '#fff4cc'
    pie4: '#ffccd5'
    pieSectionTextColor: '#333E48'
    pieOuterStrokeWidth: '3px'
    primaryTextColor: '#333E48'
---
pie showData
  title Effort by example activity
  "Syntax" : 34
  "Color config" : 24
  "Shapes" : 18
  "Validation" : 24
