---
config:
  theme: base
  themeVariables:
    fontFamily: "'Open Sans', arial, sans-serif"
    primaryColor: '#cdf3ff'
    primaryTextColor: '#333E48'
    primaryBorderColor: '#007298'
    lineColor: '#45842a'
    secondaryColor: '#fff4cc'
    tertiaryColor: '#f9ccff'
---
venn-beta
  title "Coverage"
  set Source["MMD"]:28
  set Markdown["MD"]:28
  set Styled["Style"]:24
  union Source,Markdown["Pair"]:22
  union Source,Styled["Theme"]:18
  union Markdown,Styled["Render"]:18
  union Source,Markdown,Styled["All"]:14
  style Source fill:#cdf3ff,stroke:#007298,color:#333E48,fill-opacity:0.7
  style Markdown fill:#dbffcc,stroke:#45842a,color:#333E48,fill-opacity:0.7
  style Styled fill:#fff4cc,stroke:#994a00,color:#333E48,fill-opacity:0.7
